=== carbon-14/Carbon/data/materials/program.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" >

<xs:complexType name="TextureType">
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="sampler" type="xs:string" use="required"/>
    <xs:attribute name="layout" type="xs:nonNegativeInteger" use="required"/>
    <xs:attribute name="default" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="ParameterType">
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="layout" type="xs:nonNegativeInteger" use="required"/>
    <xs:attribute name="default" type="xs:string" use="required"/>
    <xs:attribute name="desc" type="xs:string" use="optional"/>
</xs:complexType>

<xs:complexType name="ValueType">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="ref" type="xs:IDREF" use="required"/>
        </xs:extension>
     </xs:simpleContent>
</xs:complexType>

<xs:simpleType name="ColorType">
    <xs:restriction base="xs:string"/>
</xs:simpleType>

<xs:complexType name="PhongType">
    <xs:attribute name="diffuse" type="ColorType" default="1 1 1 1"/>
    <xs:attribute name="specular" type="ColorType" default="1 1 1 1"/>
    <xs:attribute name="ambient" type="ColorType" default="1 1 1 1"/>
    <xs:attribute name="emission" type="ColorType" default="0 0 0 0"/>
    <xs:attribute name="shininess" type="xs:decimal" default="1"/>
</xs:complexType>

<xs:complexType name="SetType">
    <xs:sequence>
        <xs:element name="value" type="ValueType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="phong" type="PhongType"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
</xs:complexType>

<xs:complexType name="DescriptionType">
    <xs:sequence>
        <xs:element name="texture" type="TextureType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="parameter" type="ParameterType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="SetList">
    <xs:sequence>
        <xs:element name="set" type="SetType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:element name="program">
    <xs:complexType>
        <xs:all>
            <xs:element name="description" type="DescriptionType"/>
            <xs:element name="sets" type="SetList"/>
        </xs:all>
    </xs:complexType>
</xs:element>

</xs:schema>

=== carbon-14/Carbon/data/materials/overlay.xml
<?xml version="1.0" encoding="utf-8"?>
<program xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=". program.xsd">
    <description>
        <textures>
            <texture id="GBufferDepth" sampler="LinearSampler" layout="0" default="default_c.png"/>
            <texture id="GBufferNormal" sampler="LinearSampler" layout="1" default="default_n.png"/>
            <texture id="GBufferColor" sampler="LinearSampler" layout="2" default="default_c.png"/>
            <texture id="EnvMap" sampler="LinearSampler" layout="3" default="default_c.png"/>
            <texture id="EnvMapBlur" sampler="LinearSampler" layout="4" default="default_c.png"/>
            <texture id="LightTexture" sampler="LinearSampler" layout="5" default="default_c.png"/>
        </textures>
        <parameters/>
    </description>
    <sets/>
</program>

=== carbon-14/Carbon/data/materials/level6.xml
<?xml version="1.0" encoding="utf-8"?>
<program xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=". program.xsd">
    <description>
        <textures>
            <texture id="colorMap" sampler="LinearSampler" layout="0" semantic="color" default="default_c.png"/>
            <texture id="normalMap" sampler="LinearSampler" layout="1" semantic="normal" default="default_n.png"/>
        </textures>
        <parameters>
            <parameter id="SpecParams" layout="0" desc="intensity, power">1 4</parameter>
        </parameters>
    </description>
    <sets>
        <set id="stone">
            <value ref="SpecParams">0.1 4</value>
        </set>
        <set id="marble">
            <value ref="SpecParams">1 16</value>
        </set>
        <set id="metal">
            <value ref="SpecParams">0.5 8</value>
        </set>
        <set id="fabric">
            <value ref="SpecParams">0.01 1</value>
        </set>
    </sets>
</program>

=== carbon-14/Carbon/data/shaders/level5.xml
<?xml version="1.0" encoding="utf-8"?>
<program xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="program.xsd">
    <description>
        <texture id="colorMap" sampler="LinearSampler" layout="0" default="default_c.png"/>
        <texture id="normalMap" sampler="LinearSampler" layout="1" default="default_n.png"/>
        <parameter id="specParams" layout="0" desc="intensity, shininess, unused, unused"/>
        <parameter id="emissiveColor" layout="1" desc="rgba"/>
    </description>
    <sets>
        <set id="wall">
            <value ref="specParams">0.25 4</value>
            <value ref="emissiveColor">0 0 0 1</value>
            <phong>
                <diffuse>1 1 1 1</diffuse>
                <specular>0.25 0.25 0.25 1</specular>
                <ambient>1 1 1 1</ambient>
                <emission>0 0 0 1</emission>
                <shininess>6</shininess>
            </phong>
        </set>
        <set id="sphere">
            <value ref="specParams">1 32</value>
            <value ref="emissiveColor">1 0.5 0.25</value>
            <phong>
                <diffuse>1 1 1 1</diffuse>
                <specular>1 1 1 1</specular>
                <ambient>1 1 1 1</ambient>
                <emission>1 0.5 0.25 1</emission>
                <shininess>50</shininess>
            </phong>
        </set>
    </sets>
</program>

=== carbon-14/Carbon/data/materials/level5.xml
<?xml version="1.0" encoding="utf-8"?>
<program xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=". program.xsd">
    <description>
        <texture id="colorMap" sampler="LinearSampler" layout="0" default="default_c.png"/>
        <texture id="normalMap" sampler="LinearSampler" layout="1" default="default_n.png"/>
        <parameter id="specParams" layout="0" default="1 1" desc="intensity, shininess"/>
        <parameter id="emissiveColor" layout="1" default="0 0 0 1" desc="rgba"/>
    </description>
    <sets>
        <set id="wall">
            <value ref="specParams">0.25 4</value>
            <value ref="emissiveColor">0 0 0 1</value>
            <phong diffuse="1 1 1 1" specular="25 0.25 0.25 1" ambient="1 1 1 1" emission="0 0 0 1" shininess="6"/>
        </set>
        <set id="sphere">
            <value ref="specParams">1 32</value>
            <value ref="emissiveColor">1 0.5 0.25</value>
            <phong diffuse="1 1 1 1" specular="1 1 1 1" ambient="1 1 1 1" emission="1 0.5 0.25 1" shininess="50" />
        </set>
    </sets>
</program>

=== carbon-14/Carbon/data/materials/geomCN.xml
<?xml version="1.0" encoding="utf-8"?>
<program xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=". program.xsd">
    <description>
        <textures>
            <texture id="colorMap" sampler="LinearSampler" layout="0" semantic="color" default="default_c.png"/>
            <texture id="normalMap" sampler="LinearSampler" layout="1" semantic="normal" default="default_n.png"/>
        </textures>
        <parameters/>
    </description>
    <sets>
        <set id="stone"/>
        <set id="marble"/>
        <set id="metal"/>
        <set id="fabric"/>
    </sets>
</program>
